# Generated by Django 5.0.4 on 2024-04-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otherfields',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='static\\profile_images'),
        ),
    ]
