# Generated by Django 5.0.4 on 2024-04-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_otherfields_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otherfields',
            name='cni',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
