# Generated by Django 5.0.4 on 2024-04-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_otherfields_cni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otherfields',
            name='cni',
            field=models.CharField(default='', max_length=10),
        ),
    ]
