# Generated by Django 5.0.4 on 2024-04-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_otherfields_cni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_otherfields',
            name='cni',
        ),
    ]
