# Generated by Django 5.0.4 on 2024-04-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_otherfields_cni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_otherfields',
            old_name='cni',
            new_name='cni1',
        ),
    ]
