# Generated by Django 5.0.4 on 2024-04-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_cni_user_otherfields_cni1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_otherfields',
            name='cni1',
        ),
        migrations.RemoveField(
            model_name='user_otherfields',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='user_otherfields',
            name='user',
        ),
    ]
