# Generated by Django 5.0.4 on 2024-04-23 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_user_otherfields_cni1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otherfields',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='static\\profile_images'),
        ),
        migrations.AddField(
            model_name='user_otherfields',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
