# Generated by Django 5.0.4 on 2024-04-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_otherfields_profile_image_user_otherfields_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otherfields',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
