# Generated by Django 5.0.4 on 2024-04-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_otherfields_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_otherfields',
            old_name='test',
            new_name='cni',
        ),
    ]
