# Generated by Django 5.0.4 on 2024-04-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_test_user_otherfields_cni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otherfields',
            name='cni',
            field=models.CharField(default='abcde', max_length=10, null=True),
        ),
    ]
