# Generated by Django 5.0.4 on 2024-04-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_user_otherfields_cni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_otherfields',
        ),
    ]
