# Generated by Django 5.0.4 on 2024-05-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_user_otherfields_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='static')),
                ('price', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
