# Generated by Django 5.0.4 on 2024-05-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_course_is_purchassed_coursepurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_purchassed',
        ),
        migrations.DeleteModel(
            name='CoursePurchase',
        ),
    ]
