# Generated by Django 5.0.4 on 2024-05-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, null=True)),
                ('prenom', models.CharField(max_length=30, null=True)),
                ('cni', models.CharField(max_length=10, null=True)),
                ('numero_telephone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
            ],
        ),
    ]
