# Generated by Django 5.0.4 on 2024-05-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_appointement'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointement',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
