# Generated by Django 5.0.4 on 2024-05-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_appointement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointement',
            name='message',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
