# Generated by Django 5.0.4 on 2024-05-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_appointement_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointement',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
