# Generated by Django 5.0.4 on 2024-05-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_appointement_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointement',
            name='date',
            field=models.TextField(null=True),
        ),
    ]
