# Generated by Django 5.0.4 on 2024-05-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_appointement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otherfields',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
