# Generated by Django 5.0.4 on 2024-05-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_user_otherfields_is_driver_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_driver',
            field=models.BooleanField(null=True),
        ),
    ]
