# Generated by Django 5.0.4 on 2024-05-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_driver_is_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='part',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
