# Generated by Django 5.0.4 on 2024-05-19 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_driver_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='profile_image',
        ),
        migrations.CreateModel(
            name='Driving_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('conduite de base', 'conduite de base'), ('conduite sur ville', 'conduite sur ville'), ('conduite sur circuit', 'conduite sur circuit')], max_length=30)),
                ('price_per_hour', models.IntegerField(null=True)),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver')),
            ],
        ),
    ]
