# Generated by Django 5.0.4 on 2024-05-19 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_driver_profile_image_driving_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driving_offer',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver'),
        ),
    ]
