# Generated by Django 5.0.4 on 2024-05-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_driving_offer_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driving_offer',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
