# Generated by Django 5.0.4 on 2024-05-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_bike_car_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_image',
            field=models.ImageField(null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_image',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
