# Generated by Django 5.0.4 on 2024-05-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_bike_level_car_level_truck_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_driving_offer',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='request_driving_offer',
            name='vehicle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
