# Generated by Django 5.0.4 on 2024-05-23 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_request_driving_offer_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_driving_offer',
            name='driving_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driving_offer'),
        ),
    ]
