# Generated by Django 5.0.4 on 2024-05-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_request_driving_offer_driving_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_driving_offer',
            name='is_approuved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
