# Generated by Django 5.0.4 on 2024-05-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_request_driving_offer_is_approuved'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_driving_offer',
            name='date',
            field=models.TextField(null=True),
        ),
    ]
